name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Debug: 查看替換前的 index.html 內容
      - name: Debug before replace
        run: |
          echo "===== Before Replace ====="
          grep "maps.googleapis.com/maps/api/js" index.html || echo "No Google Maps script found"
          echo "=========================="

      # 替換 API Key
